version: "3.8"
services:
  app:
    build: .
    command: bash -c "npm i && npm run dev"
    ports:
      - 8081:8081
    volumes:
      - .:/app
    depends_on:
      - postgres
    environment:
      - NODE_ENV=development

  postgres:
    image: postgres:latest
    environment:
      - POSTGRES_USER=dev
      - POSTGRES_PASSWORD=localhost
    ports:
      - 5434:5432
    volumes:
      - postgres:/var/lib/postgresql/data

volumes:
  postgres:
