version: '3.8'
services:
  app:
    build: .
    command: bash -c "npm i && npm run dev"
    ports:
      - 8081:8081
    volumes:
      - .:/app
    depends_on:
      - db
    environment:
      - DATABASE_URL=postgresql://dev:localhost@db:5432

  db:
    image: postgres:latest
    environment:
      - POSTGRES_USER=dev
      - POSTGRES_PASSWORD=localhost
